galerie:
    path: /Galerie/{page}
    controller: App\Controller\GalerieController::index
    defaults: { page: 1 }
    requirements:
        page: '\d+'
        
galerie_add:
    path: /Galerie/add
    controller: App\Controller\GalerieController::add
